### ISSUE TITLE
EOFError: Ran out of input when training

### ISSUE THREAD

**Issue by zalanfarkas** [Cyanogenoid/pytorch-vqa#17]
Hi, I got the following issue when I ran train.py. Could you please help me to fix it?

will save to logs\2019-02-21_13:49:31.pth
D:\blondie\pytorch-vqa\model.py:90: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(w)
D:\blondie\pytorch-vqa\model.py:86: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(self.embedding.weight)
D:\blondie\pytorch-vqa\model.py:44: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(m.weight)
train E000:   0% 0/3396 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 115, in main
    _ = run(net, train_loader, optimizer, tracker, train=True, prefix='train', epoch=i)
  File "train.py", line 45, in run
    for v, q, a, idx, q_len in tq:
  File "C:\Users\Konstantinos\Miniconda3\lib\site-packages\tqdm\_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "C:\Users\Konstantinos\Miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\Konstantinos\Miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\Konstantinos\Miniconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 286, in reduce_storage
    metadata = storage._share_filename_()
**RuntimeError: Couldn't map view of shared file <torch_3844_2531614511>, error code: <5>**

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Konstantinos\Miniconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
**EOFError: Ran out of input**

**Comment by Cyanogenoid** [comment]
I only tested this code on Linux, so this may be an issue with Windows https://github.com/pytorch/pytorch/issues/4239. You might be able to get around this by setting data_workers in `config.py` to be something smaller, maybe all the way down to 0.

**Comment by zalanfarkas** [comment]
It worked. Thank you!

**Comment by PriyankaJain-1998** [comment]
Can you please give the path of config.py file if not downloading this repo so what to do.
Actually i am getting same error while working with kraken.

**Comment by Cyanogenoid** [comment]
Change it here: https://github.com/Cyanogenoid/pytorch-vqa/blob/master/config.py

**Comment by PriyankaJain-1998** [comment]
I have made my own conda env for kraken and working accd to https://github.com/mittagessen/kraken
but getting this error. any idea?
